### PR TITLE
build: add new builder

### PR DESCRIPTION
**Pull request by ahhud**
Has added yet another builder

### CODE REVIEW

**Review by AlbsAgren — APPROVED** [review]

**Review by lazan — APPROVED** [review]

**Comment by lazan** [comment]
I think there might be a problem with som sort of race condition if two action runs overlap, sort of. Do you wanna check that out before we merge this?

**Comment by ahhud** [comment]
> I think there might be a problem with som sort of race condition if two action runs overlap, sort of. Do you wanna check that out before we merge this?

Please elaborate. Which actions do you see that can run overlap?

**Comment by lazan** [comment]
I started patch/1.6/docum... and patch/1.6/main a few minutes later. The last one failed to get some "state" from github. It worked when I rerun it after the first was done.

**Comment by ahhud** [comment]
Ok, so it had nothing to do with this commit but rather the general behaviour when you in your case still have three builders when your closet is still in play which this commit is mitigating?
Ok, I will have a look.

**Comment by ahhud** [comment]
Looks more like the Larsbuilders sometimes have a problem with building frontend resulting i a missing artifact. 
As it is the frontend artifact isn't even used. So I think I will remove all trace of it. But it is a separate problem and not linked to this. So I merge this needed one. And create a different issue to do some cleanup and lifecycling of versions on helper actions.

**Pull request merged**
